---
title: "data cleaning"
author: "Kailin Xu, Feiran GE"
date: "2024-12-03"
output: pdf_document
---

```{r setup, include=FALSE}
library(quanteda)
library(tidyverse)
library(lubridate)
library(topicmodels)
library(dplyr)
```


```{r}
data <- read.csv("Comments.csv")
str(data)
colnames(data)
head(data)
```

```{r}
data_cleaned <- data %>%
  filter(author != "[deleted]", comment != "[removed]")

data_cleaned <- data_cleaned %>%
  mutate(
    date = as.Date(date, format = "%Y-%m-%d"), 
    timestamp = as.POSIXct(timestamp, origin = "1970-01-01") 
  )

data_cleaned <- data_cleaned %>%
  distinct()

data_cleaned <- data_cleaned %>%
  drop_na()

data_cleaned <- data_cleaned %>%
  filter(date >= as.Date("2018-01-01") & date <= as.Date("2024-11-14"))

str(data_cleaned)
head(data_cleaned)
```

```{r}
library(dplyr)
library(lubridate)
library(stringr)

data_pre <- data_cleaned %>%

  dplyr::select(author, date, score, upvotes, downvotes, comment) %>%
  
  mutate(
    day = lubridate::ymd(date),
    month = as.numeric(lubridate::month(date, label = TRUE, abbr = TRUE)),
    year = lubridate::year(date)
  ) %>%
  

  mutate(
    comment = stringr::str_trim(
      stringr::str_to_lower(
        stringr::str_replace_all(comment, "[^a-zA-Z0-9\\s]", "")
      )
    )
  ) %>%
  
  mutate(doc_id = paste0("doc_", seq_len(n()))) %>%
  
  filter(!is.na(comment) & nchar(comment) > 10)
）
```


```{r}

glimpse(data_pre)
head(data_pre)

write.csv(cleaned_data, "cleaned_comments.csv", row.names = FALSE)
```